package com.example.myappmobile.core.navigation

object Routes {
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val FORGOT_PASSWORD = "forgot_password"
    const val VERIFICATION = "verification"

    const val HOME = "home"
    const val SEARCH = "search"
    const val SELLER = "seller"
    const val SELLER_STOREFRONT = "seller/storefront/{sellerId}"
    const val SELLER_PRODUCTS = "seller/products/{sellerId}"
    const val SELLER_BINARY_PRODUCTS = "seller/binary-products/{sellerId}"
    const val SELLER_ABOUT = "seller/about/{sellerId}"
    const val SELLER_REVIEWS = "seller/reviews/{sellerId}"
    const val SELLER_MANAGE_PRODUCTS = "seller/manage-products"
    const val SELLER_RECEIVED_ORDERS = "seller/received-orders"
    const val SELLER_ORDER_DETAIL = "seller/orders/{orderId}"
    const val WISHLIST = "wishlist"
    const val PROFILE = "profile"
    const val PERSONAL_INFORMATION = "profile/personal-information"
    const val PASSWORD_SECURITY = "profile/password-security"
    const val SAVED_ADDRESSES = "profile/saved-addresses"
    const val PAYMENT_METHODS = "profile/payment-methods"
    const val NOTIFICATIONS = "profile/notifications"
    const val STORE_CONFIGURATION = "profile/store-configuration"
    const val PAYMENTS_PAYOUTS = "profile/payments-payouts"
    const val SELLER_WITHDRAWAL = "profile/payments-payouts/withdrawal"
    const val ORDER_TRACKING = "orders/tracking"
    const val SHOP_FILTERS = "shop/filters"

    const val CART = "cart"
    const val CHECKOUT = "checkout/address"
    const val CHECKOUT_SHIPPING = "checkout/shipping"
    const val CHECKOUT_PAYMENT = "checkout/payment"
    const val CHECKOUT_CONFIRMATION = "checkout/confirmation"
    const val ROOM_USERS_TEST = "testing/room/users"
    const val ROOM_PRODUCTS_TEST = "testing/room/products"
    const val PRODUCT_DETAILS = "product_details/{productId}"

    fun sellerStorefront(sellerId: String): String = "seller/storefront/$sellerId"
    fun sellerProducts(sellerId: String): String = "seller/products/$sellerId"
    fun sellerBinaryProducts(sellerId: String): String = "seller/binary-products/$sellerId"
    fun sellerAbout(sellerId: String): String = "seller/about/$sellerId"
    fun sellerReviews(sellerId: String): String = "seller/reviews/$sellerId"
    fun sellerOrderDetail(orderId: String): String = "seller/orders/$orderId"
    fun productDetails(productId: String): String = "product_details/$productId"
}
